language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.18"
  - "5.20"
  - "5.22"
sudo:
  false
install:
    - perl -v
    - cpanm -L cpanmlibs Log::Log4perl
script: 
    - perl -Ilib -Icpanmlibs/lib/perl5 t/*.t
