language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.18"
  - "5.20"
  - "5.22"
sudo:
  false
addons:
  apt:
    packages:
    - liblog-log4perl-perl
install:
    - perl -v
script: 
    - perl -Ilib t/*.t
